### ISSUE TITLE
Won't build for Xcode 9.4

### ISSUE THREAD

**Issue by matt-green-ra** [temoki/TortoiseGraphics#33]
Hello Tomoki! I am playing with this in iOS and I'd like to also make the playgrounds run via Xcode. When I build as you recommend:

> On Xcode
> Open TortoiseGraphics.xcworkspace in Xcode.
> Build TortoiseGraphics scheme for My Mac.
> Select Playground in project navigator.
> Let's play!

It doesn't work.  I get three "Shell Script Invocation" errors: 

Any suggestions?

<img width="1100" alt="screen shot 2018-06-24 at 8 39 28 pm" src="https://user-images.githubusercontent.com/6687663/41829289-b6b2f79e-77ee-11e8-85ee-8d43fbd34002.png">

**Comment by temoki** [comment]
@matthewalangreen 

Thank you for your report. I fixed this issue and released v0.13.2.

**Comment by temoki** [comment]
@matthewalangreen https://twitter.com/STEMatthewGreen/status/1012832280140644352

It did not reproduce in Xcode 9.4.1, please give me more information.

**Comment by temoki** [comment]
@matthewalangreen 

Did you pull or re-clone?

If you'd like to disable swiftlint, remove "Run SwiftLint" build phase.

<img width="1406" alt="2018-06-30 8 29 58" src="https://user-images.githubusercontent.com/3050100/42118676-02cee93a-7c40-11e8-8d20-e38920d0e8f8.png">

**Comment by matt-green-ra** [comment]
Disabling swiftlint did it. Thank you!
