### ISSUE TITLE
writePNG(to:) method not working

### ISSUE THREAD

**Issue by matt-green-ra** [temoki/TortoiseGraphics#34]
Hello again! I'm now running the playground in Xcode and its working great. I'd like to be able to export files to png (or any filetype for that matter).  

When I run [this](https://snippets.cacher.io/snippet/5db7c8b987b18518fcf5) within Xcode, 
```
//: # With a tortoise 🐢
//: [👉 With 2 tortoises 🐢🐢](@next)
import PlaygroundSupport
import TortoiseGraphics
import CoreGraphics

let canvas = PlaygroundCanvas(frame: CGRect(x: 0, y: 0, width: 800, height: 800))
canvas.frameRate = 30
canvas.color = .white
PlaygroundPage.current.liveView = canvas

canvas.drawing { 🐢 in

    🐢.penColor(.red)
    🐢.penDown()
    

    // draw a square
//    🐢.forward(100)
//    🐢.left(90)
//    🐢.forward(100)
//    🐢.left(90)
//    🐢.forward(100)
//    🐢.left(90)
//    🐢.forward(100)
//    🐢.left(90)
    
    
    // look for repeats...
//    for i in 1 ... 4 {
//        🐢.forward(100)
//        🐢.left(90)
//    }
    
    //make it a function
//    func square() {
//        for i in 1 ... 4 {
//            🐢.left(90)
//            🐢.forward(100)
//        }
//    }
    
    // try it out
    //square()
    
    // make it an adjustable function
    func adjustableSquare(size: Double) {
        for i in 1 ... 4 {
            🐢.left(90)
            🐢.forward(size)
        }
    }
    
    
    // let's make something out of those squares
    for i in 1...90 {
        adjustableSquare(size: 100)
        🐢.left(4)
    }
    
    // Instantiate a ImageCanvas
    let canvie = ImageCanvas(size: CGSize(width: 300, height: 300))
    
    canvie.drawing { 🐢 in
        for i in 1...90 {
            adjustableSquare(size: 100)
            🐢.left(4)
        }
    }
    
    let cgImage = canvie.cgImage
    
    let image = canvie.image
    
    // this line creates the error, everything else runs great
    canvie.writePNG(to: URL(fileURLWithPath: "./image.png"))
    
  
}
```

I get the following error:

```
Playground execution failed:

error: Playground.playground:69:25: error: use of unresolved identifier 'URL'
    canvie.writePNG(to: URL(fileURLWithPath: "./image.png"))
                        ^~~

warning: Playground.playground:42:13: warning: immutable value 'i' was never used; consider replacing with '_' or removing it
        for i in 1 ... 4 {
            ^
            _

```

## Also -- Is it possible to export to an image file when running via the Playground book on iPad?

**Comment by temoki** [comment]
@matthewalangreen 

`URL` is contained in `Foundation` module, you should import `Foundation`.

```swift
import Foundation
```

**Comment by temoki** [comment]
@matthewalangreen 

Also, you need to specify the output destination URL of the file correctly. For example,

```swift
// write to your desktop.
let desktop = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Desktop")
canvie.writePNG(to: desktop.appendingPathComponent("image.png"))
```

**Comment by temoki** [comment]
@matthewalangreen 

You should define `adjustableSquare(size:)` function in `drawing` block.

```swift
canvie.drawing { 🐢 in
    
    func adjustableSquare(size: Double) {
        for i in 1 ... 4 {
            🐢.left(90)
            🐢.forward(size)
        }
    }
    
    for i in 1...90 {
        adjustableSquare(size: 100)
        🐢.left(4)
    }
}
```

**Comment by temoki** [comment]
@matthewalangreen This is full code on Xcode playground.

```swift
import TortoiseGraphics
import CoreGraphics
import Foundation

// Instantiate a ImageCanvas
let canvie = ImageCanvas(size: CGSize(width: 300, height: 300))

canvie.drawing { 🐢 in
    
    func adjustableSquare(size: Double) {
        for i in 1 ... 4 {
            🐢.left(90)
            🐢.forward(size)
        }
    }
    
    for i in 1...90 {
        adjustableSquare(size: 100)
        🐢.left(4)
    }
}

let desktop = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Desktop")
canvie.writePNG(to: desktop.appendingPathComponent("image.png"))
```

**Comment by temoki** [comment]
@matthewalangreen 

> Also -- Is it possible to export to an image file when running via the Playground book on iPad?

It is not possible. 🙇 

Where do you want to export an image file? How do you use the expored image file?

**Comment by matt-green-ra** [comment]
Thank you =). I’m going to use the image and send it through Inkscape to the AxiDraw 3. The teachers I’ll be working with will be authoring their work in iPad so I’ll just need to figure out an efficient way to get the code from each iPad to a single MacBook running the plotter.

**Comment by temoki** [comment]
@matthewalangreen :ok: I'll think about it.

**Comment by matt-green-ra** [comment]
Thanks! I'll think about it too and share whatever solutions I come up with.

**Comment by matt-green-ra** [comment]
I tested out the writePNG(to:) method with your recommendations and it worked great. Thank you!

**Comment by temoki** [comment]
@matthewalangreen

Using UIActivityViewController, you can save a drawn image to cameraroll, iCloud drive, Dropbox, and so on. You can also send the image to mac by AirDrop.
How do you think?

https://developer.apple.com/documentation/uikit/uiactivityviewcontroller

**Comment by matt-green-ra** [comment]
@temoki I like that idea! I'd say camera roll is the best because then we could choose to airdrop if we want to. Thank you!

**Comment by temoki** [comment]
@matthewalangreen I tried. Presenting UIActivityViewController on Swift Playground, it is not worked. :cry:

**Comment by matt-green-ra** [comment]
dang @temoki thanks for trying =)

**Comment by temoki** [comment]
@matthewalangreen I will think about a bit more. 🤔
