### ISSUE TITLE
Animation using CAShapeLayer

### ISSUE THREAD

**Issue by lcs-rgordon** [temoki/TortoiseGraphics#38]
Change drawing engine to animate using CAShapeLayer to improve speed and reliability. 

@temoki You may have found this before, also under the MIT license:

https://github.com/mhanlon/SwiftTurtleGraphics/blob/master/TurtleGraphics.playgroundbook/Contents/Sources/TurtleView.swift

Something to give a head start in using CAShapeLayer?

Approach taken is that each additional command adds a sub layer. 

Immediate observations:

* needs to be adapted to also run on macOS
* handles drawing of command histories differently; TortoiseGraphics is more correct

**Comment by temoki** [comment]
@lcs-rgordon Thank you! :smile:

> Approach taken is that each additional command adds a sub layer.

That approach is what I was thinking!

**Comment by temoki** [comment]
@lcs-rgordon 
I started implementation.
https://twitter.com/temoki/status/1155134680464683008

**Comment by lcs-rgordon** [comment]
@temoki That's awesome! I'm just hitting a part of my summer where I have time to try this out again. I'd be happy to take it for a spin and/or help debug.

**Comment by temoki** [comment]
@lcs-rgordon Please see [v1](https://github.com/temoki/TortoiseGraphics/tree/v1) branch. I'm still going to continue destructive changes.

**Comment by temoki** [comment]
@lcs-rgordon Hi. I want to know to whom and how my product is used. Please let me know about lcs, you and your students. How should I contact you? Email, SNS and so on.

**Comment by russellgordon** [comment]
@temoki Reach me at rgordon@lcs.on.ca – happy to describe how we used TortoiseGraphics last year and how we might use it this coming year.

**Comment by temoki** [comment]
@lcs-rgordon @russellgordon Thank you :smile: I'll send email.

**Comment by temoki** [comment]
@lcs-rgordon @russellgordon I pre-released v1.0.0-beta.1. Please try it!
