### ISSUE TITLE
Allow for custom playground live view size

### ISSUE THREAD

**Issue by lcs-rgordon** [temoki/TortoiseGraphics#41]
The [opening lines of the sample playground provided](https://github.com/temoki/TortoiseGraphics/blob/master/Playground.playground/Pages/Page1.xcplaygroundpage/Contents.swift#L7-L8) creates a live view.

There [does not seem to be a way, when using the playground live view, to set custom dimensions](https://github.com/temoki/TortoiseGraphics/blob/master/PlaygroundBook/Sources/Playground/PlaygroundCanvasLiveView.swift#L22).

For teaching purposes, I'm often having students work inside of a playground using Xcode on macOS – being able to set custom view dimensions would be helpful.

**Comment by temoki** [comment]
@lcs-rgordon 
I added new initializer `init(size: CGSize)` to `PlaygroundCanvasLiveView`.

```swift
let size = CGSize(width: 300, height: 300)
let liveView = PlaygroundCanvasLiveView(size: size)
PlaygroundPage.current.liveView = liveView
```

Please check the master branch or [1.0.0-beta.2](https://github.com/temoki/TortoiseGraphics/releases/tag/1.0.0-beta.2).
Note that you need to use the latest version 11.1 of Xcode.

**Comment by lcs-rgordon** [comment]
@temoki Works great in testing at my end. Thank-you!
